import "server-only";

import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { createClient as createSupabaseClient } from "@supabase/supabase-js";
import { env } from "@/lib/env";

// Note: Database typing intentionally omitted. The supabase-js generic
// constraints around Schema/Tables produce confusing `never` errors when
// the Database type isn't generated by the supabase CLI. We rely on the
// hand-written Row/Insert types in lib/supabase/types.ts as documentation
// and on the route-level usage to enforce shape correctness.

export async function createClient() {
  const cookieStore = await cookies();

  return createServerClient(
    env.SUPABASE_URL,
    env.SUPABASE_ANON_KEY,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll();
        },
        setAll(cookiesToSet) {
          try {
            cookiesToSet.forEach(({ name, value, options }) => {
              cookieStore.set(name, value, options);
            });
          } catch {
            // Server Component context — set cookies via Server Action / Route Handler instead.
          }
        },
      },
    },
  );
}

/**
 * Service-role client. Bypasses RLS — use ONLY in trusted server contexts.
 * Never expose to the client.
 */
export function createServiceClient() {
  return createSupabaseClient(
    env.SUPABASE_URL,
    env.SUPABASE_SERVICE_ROLE_KEY,
    {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      },
    },
  );
}
